title: US Election Map animations
description: <em></em>
logo: Personal-Works/Rplot2016.jpeg
description: <a href="https://wei-kiat-tan.github.io/weikiat98.github.io/">Return to My Profile Page</a>
theme: jekyll-theme-minimal
